build:
  info: "v3"
accounts:
  message: "Welcome to accounts APIs"
  contactDetails:
    name: "Jen Doe"
    email: "jendoe@email.com"
    role: "Business"
  onCallSupport:
    - (111) 12345-1262
    - (222) 12345-1263