spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sarmaria/Banking-Configurations.git"
          clone-on-start: true # clone the repo when config-server start or it will clone only one the first request
          default-label: main # branch to connect
          force-pull: true # local changes in the cloned config-server will be discarded on restart
          timeout: 5 # wait for 5 sec
encrypt:
  key: "AS8DW123S3D4G1V5X6N7M8B9N0"

server:
  port: 8071
